### ISSUE TITLE
Resource specific download bug

### ISSUE THREAD

**Issue by yf508** [digital-york/ncelp#158]
While downloading this resource: https://resources.ncelp.org/concern/file_sets/4q77fr34w?locale=en

Gives an error:

![image](https://user-images.githubusercontent.com/437701/57841618-cdb40a80-77c2-11e9-8825-4e2f7eab3c5f.png)

**Comment by yf508** [comment]
This bug might link to how resource_id is retrieved, e.g. in https://github.com/digital-york/ncelp/blob/master/app/views/hyrax/file_sets/_actions.html.erb#L50

**Comment by paluchas** [comment]
Just to add that I have seen this today. The error show while I was completing the survey to download the file for some other testing #171. On the 2nd attempt to download the file, I have completed the survey and all was ok. 

@yf508 I could not find any relevant information at Rails app log/production.log file.  Could this be Fedora related issue?

**Comment by paluchas** [comment]
I have traced this error at /var/log/apache2/error.log  log file. Here is the error log:
```
[ N 2019-07-04 09:41:23.6825 16575/T3 age/Cor/CoreMain.cpp:1146 ]: Checking whether to disconnect long-running connections for process 30030, application /opt/york/digilib/ncelp/current (production)
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.4/lib/active_fedora/relation/finder_methods.rb:192:in `load_from_fedora'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.4/lib/active_fedora/relation/finder_methods.rb:181:in `find_one'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.4/lib/active_fedora/relation/finder_methods.rb:234:in `find_with_ids'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.4/lib/active_fedora/relation/finder_methods.rb:52:in `find'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.4/lib/active_fedora/querying.rb:3:in `find'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/app/controllers/survey_controller.rb:12:in `submit'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/abstract_controller/base.rb:186:in `process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `block in instrument'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `instrument'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.2/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/abstract_controller/base.rb:124:in `process'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionview-5.1.6.2/lib/action_view/rendering.rb:30:in `process'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal.rb:189:in `dispatch'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_controller/metal.rb:253:in `dispatch'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:31:in `serve'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `each'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `serve'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:844:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.4/lib/active_fedora/ldp_cache.rb:26:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/flipflop-2.4.0/lib/flipflop/feature_cache.rb:12:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:97:in `run_callbacks'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.2/lib/rails/rack/logger.rb:36:in `call_app'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.2/lib/rails/rack/logger.rb:24:in `block in call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/tagged_logging.rb:26:in `tagged'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/tagged_logging.rb:69:in `tagged'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.2/lib/rails/rack/logger.rb:24:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
App 26266 output: /opt/york/digilib/ncelp/releases/20190517093133/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.2/lib/rails/engine.rb:522:in `call'
App 26266 output: /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 26266 output: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
App 26266 output: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 26266 output: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 26266 output: /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by paluchas** [comment]
**Updated form troubleshooting**

Search Apache access logs for string with empty resource_id parameter

```
"GET /survey/new?resource_id=&resource_fileset_id=np193925m HTTP/1.1" 200 45968 "https://resources.ncelp.org/concern/file_sets/np193925m?locale=en"
```
Possible workaround this issue is to add a code reconstructing resource_id form the fileset_id. But we ought to understand why resource_ID is empty in the first place.
